### ISSUE TITLE
RODBC and libcurl

### ISSUE THREAD

**Issue by dmenne** [jtilly/R-travis-container-example#1]
Thank for this. Works great for most standard stuff!
I am using RODBC, and it requires libcurl which should be in 
https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise. 

Do I have to wait till something is whitelisted, or can I add this module?

Checking URLs requires 'libcurl' support in the R build
- checking package namespace information ... OK
- checking package dependencies ... ERROR

https://travis-ci.org/dmenne/dmisc2

**Comment by jtilly** [comment]
As far as I can tell, getting RODBC to work only requires a couple of header files. These are in `unixodbc-dev`. I gave it a try [here](https://travis-ci.org/jtilly/dmisc2/builds/86043566). I'm not sure why the build of your package still fails though.

As for `libcurl`, I'm not exactly sure. `libcurl3` and `libcurl4-openssl-dev` are white-listed (see [here](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)). However, even with those installed, I still get the message `Checking URLs requires 'libcurl' support in the R build`. That's not an actual error though. This has also been discussed [here](https://github.com/travis-ci/travis-ci/issues/3970).

**Comment by dmenne** [comment]
Thanks for trying. The error in your build is ok and expected, because this test is Windows-specific. Loading RODBC works for you. I will have to check what went wrong in my build.

**Comment by dmenne** [comment]
For others:

```
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - libcurl4-openssl-dev 
    - libxml2-dev
    - unixodbc-dev
    - r-recommended
    - pandoc
```
